#!/usr/bin/env bash
#transfet the file from the client to server

#check did number of args < 3.
if [ $# -lt 3 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

#case if args >= 4.
if [ $# -ge 4 ]; then
	scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3"@"$2":~/
else 
	scp -o StrictHostKeyChecking=no "$1" "$3"@"$2":~/
fi
