#!/usr/bin/env bash
#install nginx wich ll be listening on port 80

apt-get update
apt-get install -y nginx

#create the directory needed
mkdir /etc/nginx/html

#create a empty index page
touch /etc/nginx/html/index.html

echo "Hello World!" > /etc/nginx/html/index.html
#listen port 80.
printf %s "server {
    listen		80 default_server;
    listen		[::]:80 default_server;

    root		/etc/nginx/html;
    index		index.html index.htm;
}
" > /etc/nginx/sites-available/default

#restarting nginx.

service nginx restart

