#!/usr/bin/env bash
# Update the package list
sudo apt-get update

# Install HAProxy
sudo apt-get install -y haproxy

# Enable HAProxy by adding "ENABLED=1" to /etc/default/haproxy
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Configure HAProxy by adding frontend and backend settings to /etc/haproxy/haproxy.cfg
cat <<EOT | sudo tee -a /etc/haproxy/haproxy.cfg
frontend elclubourirabi.tech
        timeout client  30000
        bind 0:80
        default_backend elclubourirabi.tech_backend

backend elclubourirabi.tech_backend
        timeout connect  3000
        timeout server  30000
        balance roundrobin
        server 366279-web-01 35.153.18.223 check
        server 366279-web-02 18.234.192.79 check
EOT

# Restart HAProxy service to apply the changes
sudo service haproxy restart
