#!/usr/bin/env bash
# Configures an Nginx server to listen on port 80.

# remove the default files
rm /etc/nginx/sites-enabled/default
# overwrite the files
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

#restart nginx
service nginx restart

