#!/usr/bin/env bash
# Configures an Nginx server to listen on port 80.
# overwrite the files
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
# start nginx
service nginx start
# kill the current
kill "$(pgrep 'nginx' | head -1)"
