#!/usr/bin/env bash
# Displays "To infinity and beyond" rightway with
#+ a sleep 2 in between iterations.
#   Displays "I am invincible!!!" in between iterations.

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "I am invincible!!!"' SIGTERM 
done
