#!/usr/bin/env bash
# Parses Apache log files in list format.
#   visitors by IP and HTTP status code.
#   afichate the number of occurrences, IP, and HTTP status
#+  code of each log, in sorted order.

awk '{ print $1 " " $9}' apache-access.log | sort | uniq -c | sort -rn
