#!/usr/bin/env bash
# Displays numbers from 1 to 20 in addition to:
#   "bad luck from China" for the iteration 4th
#   "bad luck from Japan" for the iteration 9th
#   "bad luck from Italy" for the loop iteration 17th

count=1

while [ $count -le 20 ]
do
  echo "$count"
  case $count in
    "4") echo "bad luck from China";;
    "9") echo "bad luck from Japan";;
    "17") echo "bad luck from Italy";;
  esac
  (( count++ ))
done
